function showCollisionBox(pose1, pose2, params)
    color = colororder;
    
    epsilon = 1e-3;
    disc_step_box = params.boundingBox ./ ceil((params.boundingBox + epsilon) * params.mapResolution);
    [disc_grid_box_X, disc_grid_box_Y, disc_grid_box_Z] = meshgrid(...
            -params.boundingBox(1)/2 : disc_step_box(1) : params.boundingBox(1)/2, ...
            -params.boundingBox(2)/2 : disc_step_box(2) : params.boundingBox(2)/2, ...
            -params.boundingBox(3)/2 : disc_step_box(3) : params.boundingBox(3)/2);
    disc_points_box = [disc_grid_box_X(:) disc_grid_box_Y(:) disc_grid_box_Z(:)];
    [disc_point_box_corners_X, disc_point_box_corners_Y, disc_point_box_corners_Z] = ...
                                meshgrid([min(disc_grid_box_X, [], 'all') max(disc_grid_box_X, [], 'all')], ...
                                         [min(disc_grid_box_Y, [], 'all') max(disc_grid_box_Y, [], 'all')], ...
                                         [min(disc_grid_box_Z, [], 'all') max(disc_grid_box_Z, [], 'all')]);
    disc_points_box_corners = [disc_point_box_corners_X(:) disc_point_box_corners_Y(:) disc_point_box_corners_Z(:)];

    disc_points_box_corners_1 = pose1(1:3).' + disc_points_box_corners;
    disc_points_box_corners_2 = pose2(1:3).' + disc_points_box_corners;
    
    disc_box_1 = disc_points_box_corners_1([1 2 4 3 1 5 6 2 6 8 4 8 7 3 7 5 6],:);
    disc_box_2 = disc_points_box_corners_2([1 2 4 3 1 5 6 2 6 8 4 8 7 3 7 5 6],:);

    hold on
    plot3(disc_box_1(:,1), disc_box_1(:,2), disc_box_1(:,3),...
          'LineStyle', '-', 'LineWidth', 1.5, 'Color', color(1,:),...
          'Marker', 'o', ...
          'MarkerFaceColor', color(1,:), 'MarkerEdgeColor', color(1,:))
    plot3(disc_box_2(:,1), disc_box_2(:,2), disc_box_2(:,3),...
          'LineStyle', '-', 'LineWidth', 1.5, 'Color', color(4,:),...
          'Marker', 'o', ...
          'MarkerFaceColor', color(4,:), 'MarkerEdgeColor', color(4,:))
    plot3(pose1(1), pose1(2), pose1(3),...
          'LineStyle', 'none', 'LineWidth', 1.5, 'Color', color(1,:),...
          'Marker', 'o', ...
          'MarkerFaceColor', color(1,:), 'MarkerEdgeColor', color(1,:))
    plot3(pose2(1), pose2(2), pose2(3),...
          'LineStyle', 'none', 'LineWidth', 1.5, 'Color', color(4,:),...
          'Marker', 'o', ...
          'MarkerFaceColor', color(4,:), 'MarkerEdgeColor', color(4,:))
    hold off
end

